#if 0
* RenConst.h
* RC declarations
* generated by FormCalc 9.4 (7 Jun 2016) on 16-Feb-2017 13:41
#endif

#ifndef RenConst_h
#define RenConst_h

#else

	ComplexType dZGG1, dZgg3, dZgs1, dMf1(4,1), dMSfsq1(2,2,4,1)
	ComplexType dMsq11Sf1(4,1), dMsq12Sf1(4,1), dZbarfL1(4,1,1)
	ComplexType dZbarfR1(4,1,1), dZbarSf1(2,2,4,1), dZfL1(4,1,1)
	ComplexType dZfR1(4,1,1), dZSf1(2,2,4,1)
	common /varRenConst/ dZGG1, dZgg3, dZgs1, dMf1, dMSfsq1
	common /varRenConst/ dMsq11Sf1, dMsq12Sf1, dZbarfL1
	common /varRenConst/ dZbarfR1, dZbarSf1, dZfL1, dZfR1, dZSf1

#endif

