LIBS += $(LIB)

OBJS := \
  $(DIR)abbr0s.o \
  $(DIR)abbr1s.o \
  $(DIR)abbr0a.o \
  $(DIR)abbr1a.o \
  $(DIR)abbr0h.o \
  $(DIR)abbr1h1.o \
  $(DIR)abbr1h2.o \
  $(DIR)abbr1h3.o \
  $(DIR)abbr1h4.o \
  $(DIR)abbr1h5.o \
  $(DIR)abbr1h6.o \
  $(DIR)abbr1h7.o \
  $(DIR)abbr1h8.o \
  $(DIR)abbr1h9.o \
  $(DIR)abbr1h10.o \
  $(DIR)abbr1h11.o \
  $(DIR)abbr1h12.o \
  $(DIR)abbr1h13.o \
  $(DIR)abbr1h14.o \
  $(DIR)born.o \
  $(DIR)born_Sfe6.o \
  $(DIR)self_Sfe6.o \
  $(DIR)self.o \
  $(DIR)self_Sfe6_Sfe7.o \
  $(DIR)self_Sfe6_Sfe7_Sfe8.o \
  $(DIR)vert_Gen6_Sfe6.o \
  $(DIR)vert_Gen6.o \
  $(DIR)vert_Sfe6_Sfe7.o \
  $(DIR)vert_Sfe6.o \
  $(DIR)vert.o \
  $(DIR)vert_Gen6_Sfe6_Sfe7.o \
  $(DIR)vert_Sfe7.o \
  $(DIR)box_Sfe6_Sfe7.o \
  $(DIR)box_Sfe6.o \
  $(DIR)box_Gen6_Sfe6.o \
  $(DIR)box.o \
  $(DIR)pent_Sfe6_Sfe7.o \
  $(DIR)pent_Sfe6.o \
  $(DIR)SquaredME.o

$(LIB): $(LIB)($(OBJS))

$(LIB)($(OBJS)): F-squaredme.d $(DIR)vars.h

